### ISSUE TITLE
Iphone controller doest reboot when RDMmonitor sents reboot command

### ISSUE THREAD

**Issue by Pogodenhelder** [versx/iPhoneController#13]
When RDMmonitor encounters a device that is stuck, it sents a reboot command to a remote listener, in my case iphonecontroller.
However it never gets accepted, even though the 2 programs are local and port 6542 is open.
There is no error in rdmmonitor just that it sents the reboot command and also no error in the logs of iphonecontroller, it just doestn receive it it seem.

Config for rdmmonitor

----
   "allowWarnReboots": true,
    "rebootMonitorURL": ["http://127.0.0.1:6542"],
    "sendRebootAlerts": true,
    "excludeFromReboots": ["Device01","Device02"],

---

config part of iphonecontroler

---
 "host": "127.0.0.1",
  "port": 6542,
---

**Comment by versx** [comment]
Listen on the actual machine IP address not localhost/127.0.0.1
