### ISSUE TITLE
Will not handle reopen requests due to find IP failing

### ISSUE THREAD

**Issue by SenorKarlos** [versx/iPhoneController#15]
Using tag 1.2.1 as latest fails in a crash loop (next issue) but for as long as I can remember, iPC will not find device IP's. They are using WiFi for internet and USB for mac connection. I can take screenshots and handle reboots but not this.

![image](https://user-images.githubusercontent.com/10344114/114725587-9cc01580-9d0a-11eb-8fc9-b0637adda46c.png)

**Comment by unseenmagik** [comment]
I have suffered this same issue. No device IP assigned to the device. 
tried to problem solve with versx but couldn't find the route cause to why the device was not showing and IP. 
Looking at the devices in my Unifi controller, I can see the IP of the devices but I am unable to hit them

**Comment by SenorKarlos** [comment]
Same here, full unifi network (UDM, Switch, AP) and they all have IP's. it's like the Mac doesn't need to know so never get the IP's. Can we use some sort of network discovery instead of whatever it's checking now?

**Comment by versx** [comment]
> Same here, full unifi network (UDM, Switch, AP) and they all have IP's. it's like the Mac doesn't need to know so never get the IP's. Can we use some sort of network discovery instead of whatever it's checking now?

Do you have AP isolation enabled?
It sends a ping request atm. Does DCM-RL get IP addresses for you? They both use the same method of fetching it.
Full UniFi stack and more here, working just fine.

**Comment by SenorKarlos** [comment]
Not sure on isolation. Nothing I did on purpose anyway. Still never installed dcmrl, despite the numerous times I contemplated switching lol

Update and editing that email reply garbage, I just looked over everything un the unifi controller and the only 'isolation' setting I found is network isolation, and there's none set.

I just tried pinging the device from the mac terminal and it only times out. Not sure what would be blocking it, the server is attached to the same switch that the AP runs off.

**Comment by SenorKarlos** [comment]
Well LOL 🤦 I tried the ping again, and the device must have been rebooting 😂 the mac can ping phones

**Comment by versx** [comment]
> Well LOL 🤦 I tried the ping again, and the device must have been rebooting 😂 the mac can ping phones

Ok, specially it executes `ping -t 1 device_name`, try that.

**Comment by SenorKarlos** [comment]
Cannot resolve, unknown host

**Comment by versx** [comment]
> Cannot resolve, unknown host

What did you run exactly when it worked?

**Comment by SenorKarlos** [comment]
I pinged the IP address of a device, they're all named and IP's showing in Unifi

**Comment by versx** [comment]
> I pinged the IP address of a device, they're all named and IP's showing in Unifi

Did you ping the IP address or the hostname/device name?

**Comment by SenorKarlos** [comment]
"I pinged the IP address of a device" O.o

**Comment by SenorKarlos** [comment]
![image](https://user-images.githubusercontent.com/10344114/114975539-68577100-9e52-11eb-99a0-baa997937c01.png)

**Comment by versx** [comment]
> "I pinged the IP address of a device" O.o

Ok, I asked to try `ping -t 1 device_name` not the IP address.

**Comment by unseenmagik** [comment]
> > "I pinged the IP address of a device" O.o
> 
> Ok, I asked to try `ping -t 1 device_name` not the IP address.

I believe we spoke before about this @versx when we tried before. 
I can ping the IP but I can’t ping the device name. Same error as Karlos

**Comment by SenorKarlos** [comment]
Dude!!!! look at the damn screenshot!! LOL wtf

**Comment by versx** [comment]
My bad didn't see it.

**Comment by versx** [comment]
Closing since this isn't an issue with iPhoneController, but rather network configuration.
