### ISSUE TITLE
Latest tag fails in reboot loop upon receiving a request

### ISSUE THREAD

**Issue by SenorKarlos** [versx/iPhoneController#16]
Pulled latest master & built, upon launch it does this over and over. Reverted to last tag for now.

0|iPhoneController  | 10:39 [TRACE] [HTTP] Initialize
0|iPhoneController  | 10:39 [TRACE] [BOT] Start
0|iPhoneController  | 10:39 [INFO] [BOT] Connecting to Discord...
0|iPhoneController  | [2021-04-13 10:39:43 -07:00] [DSharpPlus] [Info] DSharpPlus, version 3.2.3
0|iPhoneController  | [DSharpPlus] DSharpPlus, version 3.2.3: DSharpPlus, version 3.2.3
0|iPhoneController  | 10:39 [TRACE] [HTTP] Start
0|iPhoneController  | 10:39 [INFO] [HTTP] Starting...
0|iPhoneController  | 10:39 [INFO] [HTTP] Started
0|iPhoneController  | 10:39 [DEBUG] [HTTP] Listening on port 6542...
0|iPhoneController  | 10:39 [INFO] [HTTP] Starting HttpServer request handler...
0|iPhoneController  | 10:39 [INFO] [BOT] [DISCORD] Connected.
0|iPhoneController  | 10:39 [INFO] [BOT] [DISCORD] Current Application:
0|iPhoneController  | 10:39 [INFO] [BOT] [DISCORD] Name: iPhoneController
0|iPhoneController  | 10:39 [INFO] [BOT] [DISCORD] Description:
0|iPhoneController  | 10:39 [INFO] [BOT] [DISCORD] Owner: SenorKarlos#9419
0|iPhoneController  | 10:39 [INFO] [BOT] [DISCORD] Current User:
0|iPhoneController  | 10:39 [INFO] [BOT] [DISCORD] Id: redacted
0|iPhoneController  | 10:39 [INFO] [BOT] [DISCORD] Name: redacted
0|iPhoneController  | 10:39 [INFO] [BOT] [DISCORD] Email:
0|iPhoneController  | 10:39 [INFO] [BOT] Machine Name: MacOS
0|iPhoneController  | 10:40 [INFO] [HTTP] Handling restart request for device A11-SE-a89b...
0|iPhoneController  | 10:40 [DEBUG] [BOT] Unhandled exception caught.
0|iPhoneController  | 10:40 [ERROR] [BOT] System.NullReferenceException: Object reference not set to an instance of an object.
0|iPhoneController  |    at CallSite.Target(Closure , CallSite , Dictionary\`2 , Object )
0|iPhoneController  |    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
0|iPhoneController  |    at iPhoneController.Net.HttpServer.HandleDeviceRequest(WebhookPayload payload) in /Users/senorkarlos/iPhoneController/src/Net/HttpServer.cs:line 198
0|iPhoneController  |    at iPhoneController.Net.HttpServer.RequestHandler() in /Users/senorkarlos/iPhoneController/src/Net/HttpServer.cs:line 161
0|iPhoneController  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
0|iPhoneController  | --- End of stack trace from previous location where exception was thrown ---
0|iPhoneController  |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
0|iPhoneController  | Unhandled Exception:
0|iPhoneController  | System.NullReferenceException: Object reference not set to an instance of an object.
0|iPhoneController  |    at CallSite.Target(Closure , CallSite , Dictionary\`2 , Object )
0|iPhoneController  |    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
0|iPhoneController  |    at iPhoneController.Net.HttpServer.HandleDeviceRequest(WebhookPayload payload) in /Users/senorkarlos/iPhoneController/src/Net/HttpServer.cs:line 198
0|iPhoneController  |    at iPhoneController.Net.HttpServer.RequestHandler() in /Users/senorkarlos/iPhoneController/src/Net/HttpServer.cs:line 161
0|iPhoneController  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
0|iPhoneController  | --- End of stack trace from previous location where exception was thrown ---
0|iPhoneController  |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
0|iPhoneController  | 10:40 [TRACE] [BOT] WhConfig [OwnerId=2redacted, GuildId=redacted, ChannelIds=redacted]

**Comment by versx** [comment]
Looks like the request is coming in as an `OPTIONS` vs `POST` request for some reason from DCM, and as such the received payload is empty. Likely a DCM issue vs iPC. Going to test DCM right now.

**Comment by SenorKarlos** [comment]
The requests in this case are coming from updated RDMMonitor (multi reboot retry) and work as is with last tag

**Comment by versx** [comment]
> The requests in this case are coming from updated RDMMonitor (multi reboot retry) and work as is with last tagOn Apr. 15, 2021 9:22 p.m., versx ***@***.***> wrote: Looks like the request is coming in as an OPTIONS vs POST request for some reason from DCM, and as such the received payload is empty. Likely a DCM issue vs iPC. Going to test DCM right now. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

iPC seems to work fine with Postman with the appropriate headers, which DCM has 🤔 so a little confused tbh.

**Comment by SenorKarlos** [comment]
Again, DCM isn't sending anything. This is all RDMMonitor & iPC. Not sure what else I could send along to help diagnose, lemme know if there's somethin.

**Comment by versx** [comment]
Works fine here.

**Comment by versx** [comment]
@SenorKarlos Try https://github.com/versx/iPhoneController/releases/tag/1.4.1

**Comment by versx** [comment]
Closing for no response, seems you're the only one encountering this. Feel free to reopen if it persists.
