### ISSUE TITLE
SAM option failure

### ISSUE THREAD

**Issue by hunch-13** [versx/iPhoneController#27]
sam option always seems to fail with Failed to get ECID for device XXX (uuid does display here) to reapply SAM profile

this is with useIosDeploy = true

**Comment by versx** [comment]
This is intentional when `useIosDeploy` is set to true. When it's set to false it uses `cfgutil` to get device information as well as additional information required for reapply the SAM profile that `ios-deploy` does not provide.

**Comment by hunch-13** [comment]
gotcha, may want to update the readme with that.

I think part of the issue with cfgutil is that it doesn't appear to run over ssh (and thus potentially via PM2 depending on how you start/invoke it)
